const express = require('express')

const { authRouter } = require('./auth')
const { shopsRouter } = require('./shops')
const { productsRouter } = require('./products')
const { categoriesRouter } = require('./categories')
const { employeesRouter } = require('./employees')
const { receiptsRouter } = require('./receipts')
const { analyticsRouter } = require('./analytics')
const { settingsRouter } = require('./settings')
const { customersRouter } = require('./customers')
const { usersRouter } = require('./users')
const { billingRouter } = require('./billing')
const { shopBillingRouter } = require('./shop-billing')
const { suppliersRouter } = require('./suppliers')
const { purchasesRouter } = require('./purchases')
const { supplierBillsRouter } = require('./supplier-bills')
const { expensesRouter } = require('./expenses')
const { auditRouter } = require('./audit')
const { reportsRouter } = require('./reports')
const { storefrontRouter } = require('./storefront')

const apiRouter = express.Router()

apiRouter.use('/auth', authRouter)
apiRouter.use('/shops', shopsRouter)
apiRouter.use('/shops/:shopId/products', productsRouter)
apiRouter.use('/shops/:shopId/categories', categoriesRouter)
apiRouter.use('/shops/:shopId/employees', employeesRouter)
apiRouter.use('/shops/:shopId/customers', customersRouter)
apiRouter.use('/shops/:shopId/suppliers', suppliersRouter)
apiRouter.use('/shops/:shopId/purchases', purchasesRouter)
apiRouter.use('/shops/:shopId/supplier-bills', supplierBillsRouter)
apiRouter.use('/shops/:shopId/expenses', expensesRouter)
apiRouter.use('/shops/:shopId/receipts', receiptsRouter)
apiRouter.use('/shops/:shopId/analytics', analyticsRouter)
apiRouter.use('/shops/:shopId/reports', reportsRouter)
apiRouter.use('/shops/:shopId/settings', settingsRouter)
apiRouter.use('/shops/:shopId/audit-logs', auditRouter)
apiRouter.use('/shops/:shopId/billing', shopBillingRouter)
apiRouter.use('/shops/:shopId/storefront', storefrontRouter)
apiRouter.use('/users', usersRouter)
apiRouter.use('/billing', billingRouter)

module.exports = { apiRouter }
